version: 2

defaults: &defaults
  working_directory: ~/project/ethereumjs-vm
  docker:
    - image: circleci/node:8
restore_node_modules: &restore_node_modules
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-node-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-node-{{ .Branch }}-
      - v1-node-
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: npm install
          command: npm install
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - ethereumjs-vm/
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - *restore_node_modules
      - run:
          name: Lint
          command: npm run lint
  run_blockchain_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - *restore_node_modules
      - run:
          name: testBlockchain
          command: npm run testBlockchain
workflows:
  version: 2
  install-lint-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - run_blockchain_tests:
          requires:
            - install

