name: Client
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/client

defaults:
  run:
    working-directory: packages/client

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v2
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: client
        if: ${{ matrix.node-version == 16 }}

      - run: npm run lint
  test-client-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: ['goerli']
        syncmode: ['full', 'light']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run test:cli -- --network=${{matrix.network}} --syncmode=${{matrix.syncmode}} --transports rlpx
